### ISSUE TITLE
Can't start v1.6.6

### ISSUE THREAD

**Issue by skaryshev** [Domitor/Intwenty#100]
Cannot consume scoped service 'Intwenty.Areas.Identity.Data.IntwentyUserManager' from singleton 'Microsoft.Extensions.Localization.IStringLocalizerFactory'.

IStringLocalizerFactory is added as a singleton:
services.AddSingleton<IStringLocalizerFactory, IntwentyStringLocalizerFactory>();

I am not sure how IntwentyUserManager is added, possible on services.AddDefaultIdentity

Using .NET Core 3.1.407

**Comment by jfdomitor** [comment]
What db are you running with ?

Are you using the nuget package or the release from github ?

**Comment by skaryshev** [comment]
I did git clone, then checkout v1.6.6 Played around Startup.cs and Appsettings.json. All the same result: it fails on the very first line of Main() - CreateHostBuilder()

**Comment by jfdomitor** [comment]
If you give me your Program, startup and appsetting I Will have a look

**Comment by skaryshev** [comment]
I do not need to modify anything to reproduce the issue. These commands are sufficient:
```
git checkout v1.6.6
dotnet run  --project IntwentyDemo\IntwentyDemo.csproj -f netcoreapp3.1
```

I also have dotnet 5.0 SDK installed and getting a waning about Razor package downgrade during restore phase

**Comment by skaryshev** [comment]
I found a way around the issue. It starts with the following changes:
```
diff --git a/IntwentyDemo/Properties/launchSettings.json b/IntwentyDemo/Properties/launchSettings.json
index 82265fd..416e684 100644
--- a/IntwentyDemo/Properties/launchSettings.json
+++ b/IntwentyDemo/Properties/launchSettings.json
@@ -15,9 +15,6 @@
     "IntwentyDemo": {
       "commandName": "Project",
       "launchBrowser": true,
-      "environmentVariables": {
-        "ASPNETCORE_ENVIRONMENT": "Development"
-      },
       "applicationUrl": "https://localhost:5001;http://localhost:5000"
     }
   }
```
Not sure why it does not start in Development environment

**Comment by jfdomitor** [comment]
Thanks !

I have reproduced the error, and will try to solve it in next release in a week or two.

If I checkout 1.6.6 and opens it in visual studio everything runs fine, but not with dotnet run

The problem is on modelservice = scope.ServiceProvider.GetRequiredService<IIntwentyModelService>(); line 232
in mvIntwenty.cs

**Comment by jfdomitor** [comment]
Released a new version 1.7.0, the problems should be solved.

**Comment by skaryshev** [comment]
Commenting on a closed issue. I still does not start "out of the box". After clean 
`git checkout v1.7.0`
I am getting 
```
System.ArgumentException: The 'AppId' option must be provided. (Parameter 'AppId')
   at Microsoft.AspNetCore.Authentication.Facebook.FacebookOptions.Validate()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
```
and a long stack of Authentication middleware calls

**Comment by jfdomitor** [comment]
Yes you must set the parameters in appsettings.js

"AccountsFacebookAppId": "",
    "AccountsFacebookAppSecret": "",
    "AccountsGoogleClientId": "",
    "AccountsGoogleClientSecret": ""

OR

Remove google and facebook from the AccountsAllowedList also in appsettings.js

 "AccountsAllowedList": [

    ],

**Comment by skaryshev** [comment]
I setting 
```
"AccountsAllowedList": [
      {
        "Description": "Use a local account to Login",
        "AccountType": "Local"
      }
    ]
```
was sufficient for me to start.
