### ISSUE TITLE
Empty user Menu 

### ISSUE THREAD

**Issue by skaryshev** [Domitor/Intwenty#101]
Running v1.6.6 from code. I logged in as user@intwenty.dev and expected to have access to "Intwenty Demo" applications but dropdown Menu is empty. The user belongs to "Default Org" organization and associated with "Intwenty Demo" product. What else should I check? 
admin@intwenty.dev  Menu lists applications as expected.

**Comment by jfdomitor** [comment]
I think it's a caching issue, where it builds a cache before new model data has been seeded. 
1. Check that the model is in the database (Applications etc)
2. Restart

This issue will fixed in the next version along with the dependency injection failures.

**Comment by skaryshev** [comment]
It feels more like access control issue. When logged in as user@intwenty.dev and navigate directly (in the browser without using Menu) to https://localhost:5001/Customers/List I am getting Access Denied error.
Since admin@intwenty.dev is able to see and use "Intwenty Demo" forms I believe the model is in initialized properly.
Restart does not help

**Comment by jfdomitor** [comment]
Released a new version 1.7.0, the problems should be solved.

**Comment by skaryshev** [comment]
Commenting on a closed issue. Still the same: user@intwenty.dev does not have access to "Intwenty Demo" product.

**Comment by jfdomitor** [comment]
To fix this
1. Login as admin@intwenty.dev
2. Go to Identity Management
3. Go to users, select user@intwenty.dev
4. Click the user product "Intwenty Demo"
5. Click + on system permissions to give the user rights on the system wms to the user for the product.

**Comment by skaryshev** [comment]
It works now. Thanks!
